version: "3.9"
services:
  cassandra:
    image: 'cassandra:4.1.2'
    container_name: crowdfunding_cassandra
    environment:
      - 'CASSANDRA_DC=dc1'
      - 'CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch'
      - 'CASSANDRA_CLUSTER_NAME=cluster1'
    ports:
      - '9042:9042'
    volumes:
      - '~/data/cassandra:/var/lib/cassandra'
